# Generated by Django 4.0.6 on 2022-10-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='goal',
            new_name='calorie_goal',
        ),
    ]
