# Generated by Django 4.0.6 on 2022-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_goal_profile_calorie_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calorie_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
